- name: normal start new mongo database container
  command: "docker run -d --name {{ ident }}_db_mongo -p {{ port_db_mongo }}:27017 -p {{ port_db_mongo_ssh }}:22 -v /econ/mongodata:/data/db test/test-db-latest"
  sudo: yes