- name: normal start new fetcher container
  command: "docker run -d --name {{ ident }}_econ_fetcher --link {{ ident }}_db_mongo:mongodb -p {{ port_fetcher_ssh }}:22 test/test-fetcher-latest"
  sudo: yes